version: '3.7'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: nextcloud
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud

  app:
    build: .
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    env_file:
      .env



    restart: always
